local: "local machine" {
	repo: "repo + flake"
	nix: "nix store" {
		sources
		outputs
	}
	system: "system: NixOS"
}
local.style.fill: PapayaWhip
local.style.stroke-width: 0

remote: "remote machine" {
	nix: "nix store" {
		sources
		outputs
	}
	system: "system: NixOS"
}
remote.style.fill: PapayaWhip
remote.style.stroke-width: 0

local.repo -> local.nix.sources: ALL

local.nix.sources -> local.nix.outputs: "build" { style.stroke: red }
local.nix.sources -> remote.nix.sources -> remote.nix.outputs: "build-there" { style.stroke: orange }

local.nix.sources -> local.nix.outputs -> local.system: "switch"
local.nix.sources -> local.nix.outputs -> remote.nix.outputs -> remote.system: "switch-push" {style.stroke: green }
local.nix.sources -> remote.nix.sources -> remote.nix.outputs -> remote.system: "switch-pull" {style.stroke: purple }
